### ISSUE TITLE
[NEW] World Atlas 5.0

### ISSUE THREAD

**Issue by Lugamo94** [intothisworld/Non-Game-Submissions-Queue#33]
### Media

CD - Software

### Source Title

World Atlas 5.0

### Source Title (Additional)

--

### Romanized Title

--

### Unofficial/Colloquial Title

--

### Region

Argentina

### Edition

Standard

### Version

--

### Collections

--

### Bundle?

Standalone

### Item Release Date

1995

### Work Original Release Date

Same as above

### Check below if uncertain about either of the above dates.

- [X] 'Item Release Date' Uncertain
- [ ] 'Work Original Release Date' Uncertain

### Package Serials

NULL

### Barcodes

7 798047 960199

### Disc Number - Disc Title

--

### Disc Serials

WA9806

### Languages

Spanish

### Checked languages?

Yes

### External Link(s)

[--](https://web.archive.org/web/20011129122141/http://www.bjbroker.com/bjbroker/case_atlas.htm)

### Content Type

Software

### (For Software Only)

IBM PC Compatible, Applications, Educational, Multimedia

### Special Interest Tags

Educational

### Release Context

None of the above, or unknown

### Media (Secondary)

--

### Universal Hash (SHA-1): 

--

### Non-zero data start: 

--

### Comments

[T:VOL] WORLD_ATLAS
Mirrored Mastering SID.

### Technical

```Text
System Requirements:
Processor: i486SX.
RAM: 4 MB (8 MB recommended).
CD-ROM drive speed: 2x.
Sound card: Windows-compatible.
VRAM: 1 MB.
Monitor: SVGA.
Mouse and keyboard.
Windows 3.1 or higher.

Loaded disc to confirm?: Yes.
```

### EXE Date (yyyy-MM-dd)

1995-06-20

### Errors Count

0

### Layer Ring Order

N/A (only one set of ringcodes)

### Copy-paste ringcode information here:

```text
Data Side Mastering Code (laser branded/etched): 0KYY5<1767>1631	TELTRON	77980479601	INDUSTRIA ARGENTINA
Data Side Mastering SID Code: IFPI L485
Data Side Mould SID Code: IFPI 6C04
```

### Primary Volume Descriptor (PVD) (ISO9660 FS only)

```Text
0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 31 39 39                199
0330 : 38 30 36 31 35 31 39 33  34 33 37 30 30 00 31 39   8061519343700.19
0340 : 39 38 30 36 31 35 31 39  33 35 30 35 30 30 00 00   98061519350500..
0350 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0360 : 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
```

### Permanent Information & Control (PIC)

```Text
--
```

### Header

```Text
--
```

### Protection

```Text
--
```

### SecuROM Data

```Text
--
```

### ClrMamePro Data (Track Hashes)

```xml
<rom name="WORLD_ATLAS.bin" size="511585872" crc="a5f45f62" md5="7d1fe43ec3cf9ee8e86dbcd71f391688" sha1="f1b1863bc7fd3c3d2facac0c9532a01075c18a3e" />
```

### Cuesheet

```cue
FILE "WORLD_ATLAS.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
```

### Write Offset: 

-12

### Dumping Info

```Text
Frontend Version: 3.1.5-771483ac146302cf6634037db23cd336b0d1c97a
Dumping Program: DiscImageCreator 20240401
Date: 2024-04-14 04:26:37
Manufacturer: HL-DT-ST
Model: BD-RE  WH14NS40
Firmware: 1.03
Reported Disc Type: CD-DA or CD-ROM Disc
```

### Attachments (Logs & Photos/Scans)

![img474](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/ed0d719d-654a-4b4e-9f46-6bc4501bf46d)
![img476](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/a3d94118-6cc1-43db-9db7-bc578c3d88f8)
![img478](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/d030e234-1e97-406a-ba60-bb2810030479)
![img480](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/d5c55f3c-0c21-4dcc-9976-451ff1dc9e7c)
![img482](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/97514efb-6e19-4972-8cb8-212e68761400)
[WORLD_ATLAS_logs.zip](https://github.com/intothisworld/Non-Game-Submissions-Queue/files/14969529/WORLD_ATLAS_logs.zip)
![Word Atlas v5](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/dccfb712-859e-4d84-a882-01c167f8dbff)

### Photos Visibility Preference?

Openly visible on media entry page

**Comment by intothisworld** [comment]
Hey Lugamo, same request with this submission please. If you could redump with Redumper, that would be very helpful. Sorry again for the trouble, but much appreciated.

**Comment by intothisworld** [comment]
Also a final note, if your previous submissions sent in your forum messages were dumped with DIC as well, don't worry about redumping those with Redumper. If there are specific issues that pop up, we may ask for a redump, but ultimately I don't want to burden you unnecessarily. I know that you've already put a ton of work into pulling everything together.

**Comment by Lugamo94** [comment]
[Disc Not Detected_logs.zip](https://github.com/intothisworld/Non-Game-Submissions-Queue/files/15112968/Disc.Not.Detected_logs.zip)
