### ISSUE TITLE
[NEW] MacFormat n.º 23

### ISSUE THREAD

**Issue by Lugamo94** [intothisworld/Non-Game-Submissions-Queue#35]
### Media

CD - Software

### Source Title

MacFormat n.º 23

### Source Title (Additional)

Macromedia xRes Versión 2.0 completa

### Romanized Title

--

### Unofficial/Colloquial Title

--

### Region

Spain

### Edition

Standard

### Version

--

### Collections

--

### Bundle?

Standalone

### Item Release Date

1997

### Work Original Release Date

Same as above

### Check below if uncertain about either of the above dates.

- [ ] 'Item Release Date' Uncertain
- [ ] 'Work Original Release Date' Uncertain

### Package Serials

Unknown

### Barcodes

8 414090 103466 00023

### Disc Number - Disc Title

--

### Disc Serials

NULL

### Languages

No language

### Checked languages?

No

### External Link(s)

--

### Content Type

Software

### (For Software Only)

Apple Macintosh, Applications, Multimedia

### Special Interest Tags

Art, Creative Resources

### Release Context

Covermounts

### Media (Secondary)

CD

### Universal Hash (SHA-1): 

--

### Non-zero data start: 

--

### Comments

[T:VOL] MF 23 Gráfico
-----------------------
SHA-256 file hash: 9a0813685a685ab02f283604478f4354edd9518c9408424cc00ca88858076892.

I chose "Art" in special interests because the main attraction of this coverdisc is software for graphic artists. If this is incorrect, feel free to change it to a more suitable option.

### Contents

[T:X]
<u>Digital Art (Arte Digital)</u>:
Contributions from the readers of MacFormat.

<b>Software</b>:

<u>Macromedia xRes v2.0 Special Edition</u>.

<u>Image editing (Edición de imágenes)</u>:
Color It! 3.2.
Fractal Design's Dabbler Interactive Tour.
Fractal Design Painter 4.0.
PhotoFix v3.2.3v1.
Specular Collage 2.0.
Macromedia xRes 3.0 Demo.

<u>Illustration (Ilustración)</u>:
CorelDRAW 6.0 Working Model.
Fractal Design Expression 1.0.2.
Macromedia FreeHand 7 Demo.
Alias Research's Sketch! v2.0 Demonstration.
Stencil It! Demo.
ClarisDraw 1.0Βv1 Trial.

<u>3D Graphics (Gráficos 3D)</u>:
ElectricImage Animation System v2.7.
Macromedia Extreme 3D 1.0.
form·z RenderZone v2.8.0g3.
Specular Infini-D 3.5 Demo.
MiniCad 6.0.1 Demo.
Sculpt 3D 4.1 Demo.
3D World 2.0 Demo.
Tree Professional 3.0.
DesignWorkshop 1.1 Demo.

<u>QuickTime 2.5</u>.

<u>Macromedia ShockWave v5</u>.

### Technical

```Text
System Requirements: Classic Mac OS
Platform/Architecture Compatibility: Mac(m68k), Mac(PowerPC)
Loaded disc to confirm?: Yes
```

### EXE Date (yyyy-MM-dd)

--

### Errors Count

0

### Layer Ring Order

N/A (only one set of ringcodes)

### Copy-paste ringcode information here:

```text
Data Side Mastering Code (laser branded/etched): GEMA O. D.	MACFORMAT23GRAFICOS	@1$
Data Side Mould SID Code: IFPI 3203
```

### Primary Volume Descriptor (PVD) (ISO9660 FS only)

```Text
--
```

### Permanent Information & Control (PIC)

```Text
--
```

### Header

```Text
--
```

### Protection

```Text
--
```

### SecuROM Data

```Text
--
```

### ClrMamePro Data (Track Hashes)

```xml
<rom name="MF 23 Gráficos.bin" size="763134624" crc="a29d113b" md5="384665fd1e1a413377b273e4b925120e" sha1="830c45e5ae540b733be18a9c67d43837b5ad025a" />
```

### Cuesheet

```cue
FILE "MF 23 Gráficos.bin" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
```

### Write Offset: 

-22

### Dumping Info

```Text
Dumping Program: DiscImageCreator 20240101
Date: 2024-03-11 12:48:57
Manufacturer: HL-DT-ST
Model: BD-RE  WH14NS40
Firmware: 1.03
Reported Disc Type: CD-DA or CD-ROM Disc
```

### Attachments (Logs & Photos/Scans)

![Macromedia xRes Versión 2 0 completa (Apple Macintosh) (Spain) - Cover Front](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/c4a94d69-51ab-4c99-86b1-43e7f55a7454)
![Macromedia xRes Versión 2 0 completa (Apple Macintosh) (Spain) - Cover Back](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/599f67ed-54d0-4174-8bf1-5f55aedf42b7)
![Macromedia xRes Versión 2 0 completa (Apple Macintosh) (Spain) - Compact Disc](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/19b94ee9-4605-4ae9-afc9-e5f7df834097)
![Macromedia xRes Versión 2 0 completa (Apple Macintosh) (Spain) - Data Side Ring](https://github.com/intothisworld/Non-Game-Submissions-Queue/assets/166972693/d278ddb7-b184-43d7-a080-3779e1ac32a9)
[Macromedia xRes Versión 2.0 completa (Spain) - DiscImageCreator logs.zip](https://github.com/intothisworld/Non-Game-Submissions-Queue/files/15053247/Macromedia.xRes.Version.2.0.completa.Spain.-.DiscImageCreator.logs.zip)

### Photos Visibility Preference?

Openly visible on media entry page

**Comment by intothisworld** [comment]
There are a few factors at play with this dump that are a bit concerning. I sent you a message in the No-Intro forums with specific details, but ultimately me and the other mods agree that a redump with Redumper rather than DIC would be a good idea for this disc. Feel free to just include new dump logs in a follow-up comment rather than creating an all-new Github issue. Thank you and sorry for the extra trouble.

**Comment by Lugamo94** [comment]
[Disc Not Detected_logs.zip](https://github.com/intothisworld/Non-Game-Submissions-Queue/files/15112785/Disc.Not.Detected_logs.zip)
